### PR TITLE
added Dice Combinations in Dynamic Programming

### PR DESCRIPTION
**Pull request by jindalhitesh2904**

### CODE REVIEW

**Comment by TheAnshul756** [comment]
remove unwanted snippets and comment your logic.

**Comment by jindalhitesh2904** [comment]
> remove unwanted snippets and comment your logic.

ok

**Comment by jindalhitesh2904** [comment]
> remove unwanted snippets and comment your logic.

done

**Comment by TheAnshul756** [comment]
great work.

**Pull request merged**
